name: transBind
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0
  - pytorch-cuda=11.8
  - numpy
  - scikit-learn
  - h5py
  - pandas
  - jupyter
  - matplotlib
  - pip
  - pip:
    - pytorch-lightning>=2.0
    - tensorboard
    - biopython